name: Create and Upload SVG Sprites

on:
  workflow_dispatch:
    inputs:
      custom_tag:
        description: "Custom Tag for Release"
        type: string
        required: false
        default: ""
      new_assets_only:
        description: Overwrite Previous Released Assets
        type: boolean
        required: false
        default: false
      custom_previous:
        description: "Custom Previous Release"
        type: string
        required: false
        default: "0.0.0"

permissions:
  id-token: write
  contents: write

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      use_version: ${{ steps.check.outputs.use_version }}
      release_version: ${{ steps.check.outputs.release_version }}
      release_exists: ${{steps.check_asset.outputs.release_exists}}
      asset_exists: ${{steps.check_asset.outputs.asset_exists}}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check the version
        id: check
        run: |
          CURRENT_VERSION=$(jq -r .version package.json)
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          LATEST_VERSION=${LATEST_TAG#v}

          echo "$LATEST_VERSION - $CURRENT_VERSION"

          if [ "$LATEST_VERSION" != "$CURRENT_VERSION" ]; then
            echo "use_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
            DEFAULT_RELEASE=$CURRENT_VERSION
          else
            echo "use_version=$LATEST_VERSION" >> $GITHUB_OUTPUT
            DEFAULT_RELEASE=$LATEST_VERSION
          fi

          CUSTOM_TAG="${{ inputs.custom_tag }}"
          if [ -n "$CUSTOM_TAG" ]; then
            CLEAN_TAG=${CUSTOM_TAG#v}
            echo "release_version=$CLEAN_TAG" >> $GITHUB_OUTPUT
          else
            echo "release_version=$DEFAULT_RELEASE" >> $GITHUB_OUTPUT
          fi

      - name: Check latest release asset
        id: check_asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          CUSTOM_TAG="${{ inputs.custom_previous }}"
          CLEAN_TAG=${CUSTOM_TAG#v}

          ASSET_NAME=SVG-sprites-only-v$CLEAN_TAG.zip

          if gh release view "v$CLEAN_TAG" > /dev/null 2>&1; then
            echo "Release found."

            echo "release_exists=true" >> "$GITHUB_OUTPUT"

            # Check whether the asset exists
            if gh release view "v$CLEAN_TAG" \
              --json assets \
              --jq '.assets[].name' |
              grep -Fxq "$ASSET_NAME"; then

              echo "Asset found: $ASSET_NAME"
              echo "asset_exists=true" >> "$GITHUB_OUTPUT"

            else
              echo "Asset not found: $ASSET_NAME"
              echo "asset_exists=false" >> "$GITHUB_OUTPUT"
            fi

          else
            echo "Release not found: v$CLEAN_TAG"

            echo "release_exists=false" >> "$GITHUB_OUTPUT"
            echo "asset_exists=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Prepare dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          CUSTOM_TAG="${{ inputs.custom_previous }}"
          CLEAN_TAG=${CUSTOM_TAG#v}

          ASSET_NAME=SVG-sprites-only-v$CLEAN_TAG.zip

          set -e

          rm -rf dist
          mkdir -p dist

          if [ "${{ steps.check_asset.outputs.asset_exists }}" = "true" ]; then
            echo "Asset exists."
            echo "Downloading $ASSET_NAME..."

            mkdir -p /tmp/release-assets

            gh release download "v$CLEAN_TAG" \
              --pattern "$ASSET_NAME" \
              --dir /tmp/release-assets

            echo "Extracting asset..."

            unzip -q \
              "/tmp/release-assets/$ASSET_NAME" \
              -d dist

            echo "dist prepared from release asset."

          else
            echo "Asset does not exist."
            echo "Keeping dist empty."
          fi

      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: prepared-dist
          path: dist/
          include-hidden-files: true
          if-no-files-found: warn

  create_sprites:
    needs: setup
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download prepared dist
        uses: actions/download-artifact@v4
        with:
          name: prepared-dist
          path: dist/

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install dependencies
        working-directory: ./downloader
        run: npm ci

      - name: Build Project
        working-directory: ./downloader
        run: npm run build

      - name: Create SVG Sprites
        working-directory: ./downloader
        run: |

          if [ "${{ inputs.new_assets_only }}" = "true" ]; then
            echo "Using overwriting assets..."

            npm run svg-sprites -- --newOnly=true

          else
            echo "Using force new assets.."

            npm run svg-sprites
          fi

      - name: Create ZIP for files
        run: |
          VERSION="${{ needs.setup.outputs.release_version }}"
          ZIP_NAME="SVG-sprites-only-v$VERSION.zip"
          TAG_NAME="v$VERSION"

          cd dist
          zip -r "../$ZIP_NAME" sprites/
          cd ..

          if gh release view "$TAG_NAME" &>/dev/null; then
            echo "Release $TAG_NAME already exists. Overwriting asset..."
            gh release upload "$TAG_NAME" "$ZIP_NAME" --clobber
          else
            echo "Release $TAG_NAME does not exists. Creating new release..."
            gh release create "$TAG_NAME" "$ZIP_NAME" \
              --title "Font Awesome Pro+ $TAG_NAME"
          fi
