name: Create and Upload SVG Sprites

on:
  workflow_dispatch:
    inputs:
      custom_tag:
        description: "Custom Tag for Release"
        type: string
        required: false
        default: ""

permissions:
  id-token: write
  contents: write

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      use_version: ${{ steps.check.outputs.use_version }}
      release_version: ${{ steps.check.outputs.release_version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check the version
        id: check
        run: |
          CURRENT_VERSION=$(jq -r .version package.json)
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          LATEST_VERSION=${LATEST_TAG#v}

          echo "$LATEST_VERSION - $CURRENT_VERSION"

          if [ "$LATEST_VERSION" != "$CURRENT_VERSION" ]; then
            echo "use_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
            DEFAULT_RELEASE=$CURRENT_VERSION
          else
            echo "use_version=$LATEST_VERSION" >> $GITHUB_OUTPUT
            DEFAULT_RELEASE=$LATEST_VERSION
          fi

          CUSTOM_TAG="${{ inputs.custom_tag }}"
          if [ -n "$CUSTOM_TAG" ]; then
            CLEAN_TAG=${CUSTOM_TAG#v}
            echo "release_version=$CLEAN_TAG" >> $GITHUB_OUTPUT
          else
            echo "release_version=$DEFAULT_RELEASE" >> $GITHUB_OUTPUT
          fi

  create_sprites:
    needs: setup
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install dependencies
        working-directory: ./downloader
        run: npm ci

      - name: Build
        working-directory: ./downloader
        run: npm run svg-sprites

      - name: Create ZIP for files
        run: |
          VERSION="${{ needs.setup.outputs.release_version }}"
          ZIP_NAME="SVG-sprites-only-v$VERSION.zip"
          TAG_NAME="v$VERSION"

          cd dist
          zip -r "../$ZIP_NAME" sprites/
          cd ..

          if gh release view "$TAG_NAME" &>/dev/null; then
            echo "Release $TAG_NAME already exists. Overwriting asset..."
            gh release upload "$TAG_NAME" "$ZIP_NAME" --clobber
          else
            echo "Release $TAG_NAME does not exists. Creating new release..."
            gh release create "$TAG_NAME" "$ZIP_NAME" \
              --title "Release $TAG_NAME" \
              --generate-notes
          fi
